# Generated by Django 5.0.6 on 2024-05-17 08:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='harvest',
            old_name='comments',
            new_name='harvest_comments',
        ),
        migrations.RenameField(
            model_name='sowing',
            old_name='comments',
            new_name='sowing_comments',
        ),
        migrations.RenameField(
            model_name='yearreview',
            old_name='comments',
            new_name='review_comments',
        ),
        migrations.AlterField(
            model_name='harvest',
            name='end_month',
            field=models.IntegerField(choices=[(0, 'January'), (1, 'February'), (2, 'March'), (3, 'April'), (4, 'May'), (5, 'June'), (6, 'July'), (7, 'August'), (8, 'September'), (9, 'October'), (10, 'November'), (11, 'December')], validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(11)]),
        ),
        migrations.AlterField(
            model_name='harvest',
            name='start_month',
            field=models.IntegerField(choices=[(0, 'January'), (1, 'February'), (2, 'March'), (3, 'April'), (4, 'May'), (5, 'June'), (6, 'July'), (7, 'August'), (8, 'September'), (9, 'October'), (10, 'November'), (11, 'December')], validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(11)]),
        ),
        migrations.AlterField(
            model_name='sowing',
            name='depth_cm',
            field=models.DecimalField(decimal_places=1, max_digits=3),
        ),
        migrations.AlterField(
            model_name='sowing',
            name='end_month',
            field=models.IntegerField(choices=[(0, 'January'), (1, 'February'), (2, 'March'), (3, 'April'), (4, 'May'), (5, 'June'), (6, 'July'), (7, 'August'), (8, 'September'), (9, 'October'), (10, 'November'), (11, 'December')], validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(11)]),
        ),
        migrations.AlterField(
            model_name='sowing',
            name='method',
            field=models.CharField(blank=True, choices=[('IS', 'Indirect Sowing'), ('DS', 'Direct Sowing'), ('O', 'Other')], max_length=3),
        ),
        migrations.AlterField(
            model_name='sowing',
            name='row_spacing_cm',
            field=models.DecimalField(decimal_places=1, max_digits=4),
        ),
        migrations.AlterField(
            model_name='sowing',
            name='spacing_cm',
            field=models.DecimalField(decimal_places=1, max_digits=4),
        ),
        migrations.AlterField(
            model_name='sowing',
            name='start_month',
            field=models.IntegerField(choices=[(0, 'January'), (1, 'February'), (2, 'March'), (3, 'April'), (4, 'May'), (5, 'June'), (6, 'July'), (7, 'August'), (8, 'September'), (9, 'October'), (10, 'November'), (11, 'December')], validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(11)]),
        ),
        migrations.AlterField(
            model_name='tending',
            name='end_month',
            field=models.IntegerField(choices=[(0, 'January'), (1, 'February'), (2, 'March'), (3, 'April'), (4, 'May'), (5, 'June'), (6, 'July'), (7, 'August'), (8, 'September'), (9, 'October'), (10, 'November'), (11, 'December')], validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(11)]),
        ),
        migrations.AlterField(
            model_name='tending',
            name='start_month',
            field=models.IntegerField(choices=[(0, 'January'), (1, 'February'), (2, 'March'), (3, 'April'), (4, 'May'), (5, 'June'), (6, 'July'), (7, 'August'), (8, 'September'), (9, 'October'), (10, 'November'), (11, 'December')], validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(11)]),
        ),
    ]
