# Generated by Django 5.0.6 on 2024-05-20 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_useryear_alter_plantingyear_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantingyear',
            name='harvested',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plantingyear',
            name='sowed',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plantingyear',
            name='transferred',
            field=models.DateField(blank=True, null=True),
        ),
    ]
