# Generated by Django 5.0.6 on 2024-05-21 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_plantingyear_harvested_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='harvest',
            old_name='end_month',
            new_name='end_harvest_month',
        ),
        migrations.RenameField(
            model_name='harvest',
            old_name='start_month',
            new_name='start_harvest_month',
        ),
        migrations.RenameField(
            model_name='sowing',
            old_name='end_month',
            new_name='end_sowing_month',
        ),
        migrations.RenameField(
            model_name='sowing',
            old_name='start_month',
            new_name='start_sowing_month',
        ),
    ]
